name: Semantic Versioning

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
