name: Tests

on: push

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:12-alpine'
    steps:
    - uses: actions/checkout@v1
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
